apiVersion: v1
kind: Service
metadata:
  labels:
    app: jitsi
  name: jvb
spec:
  type: NodePort
  ports:
  - name: udp
    port: 30005
    nodePort: 30005
    protocol: UDP
    targetPort: 30005
  - name: tcp
    port: 30006
    nodePort: 30006
    protocol: TCP
    targetPort: 30006
  selector:
    service: jvb
